version: "3.9"

services: 
  api:
    # env_file: passed via command
    build:
      context: .
      dockerfile: ./Docker/Dockerfile.${NODE_ENV}
    volumes:
      - .:/home/src/backend
    ports:
      - "3333:3333"
      - "9229:9229"
      - "9339:9339"
    depends_on:
      - psql_db
      - redis
    restart: always
    stdin_open: true
    tty: true
  psql_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=${PG_USERNAME}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
    ports:
      - "5432:5432"
    volumes:
      - db_volume:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
volumes:
  db_volume:
  redis_volume: